pdf = fpdf()
    pdf.add_page()
    pdf.set_font("Arial", size = 15)
    pdf.cell(200, 10, txt = "Funrento",ln = 1, align = 'C')
    pdf.cell(200, 10, txt = "Invoice",ln = 2, align = 'C')
    pdf.output("GFG.pdf")