# Generated by Django 4.0.3 on 2022-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('Product_Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Product_Price', models.CharField(max_length=200)),
                ('Product_Quantity', models.IntegerField()),
            ],
        ),
    ]
